// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmnnifylxyzkfiuatjrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imptbm5pZnlseHl6a2ZpdWF0anJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNzAwNzQsImV4cCI6MjA3Mzg0NjA3NH0.UGsvSBY6vs80UXTb41NwiV_qCQz7Lm8ogO52W7pTgvQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});